-- Run once in the Supabase SQL editor.
create table if not exists public.interest_leads (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  source text not null default 'website',
  created_at timestamptz not null default now()
);

alter table public.interest_leads enable row level security;

-- No public policies are intentional. Website inserts use the server-only service role.
create index if not exists interest_leads_created_at_idx
  on public.interest_leads (created_at desc);

insert into storage.buckets (id, name, public)
values ('impact-documents', 'impact-documents', false)
on conflict (id) do update set public = false;
